server:
  port: 9191

spring:
  redis:
    host: redis
    port: 6379
  application:
    name: cloud-gateway
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296},classpath:application.yaml
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/userServiceFallback
        - id: department-service
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: department-service
                fallbackUri: forward:/departmentServiceFallback
            - name: Retry
              args:
                retries: 3
                statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, SERVICE_UNAVAILABLE
                methods: GET,POST
      circuitbreaker:
        resilience4j:
          enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
    instances:
      USER-SERVICE:
        baseConfig: default
      DEPARTMENT-SERVICE:
        baseConfig: default